"""Refactor team

Revision ID: 0af6756b936d
Revises: d50ba11e460c
Create Date: 2025-07-17 11:06:44.627180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af6756b936d'
down_revision: Union[str, None] = 'd50ba11e460c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Team_ibfk_2', 'Team', 'Player', ['CreatePlayerId'], ['Id'])
    op.create_foreign_key('Team_ibfk_1', 'Team', 'Region', ['RegionId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Team_ibfk_1', 'Team', type_='foreignkey')
    op.drop_constraint('Team_ibfk_2', 'Team', type_='foreignkey')
    # ### end Alembic commands ###
