"""change user nullable

Revision ID: 0c69949bd696
Revises: 715590025621
Create Date: 2025-07-15 10:22:42.535742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c69949bd696'
down_revision: Union[str, None] = '715590025621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'UserPhoto',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='用户头像路径')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'UserPhoto',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='用户头像路径')
    # ### end Alembic commands ###
