"""Update Database

Revision ID: 4fe45c81dc14
Revises: a0be69ff9d01
Create Date: 2025-07-19 09:33:57.530953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4fe45c81dc14'
down_revision: Union[str, None] = 'a0be69ff9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Region', 'Name',
               existing_type=mysql.VARCHAR(length=255),
               comment='赛区名',
               existing_nullable=False)
    op.alter_column('Region', 'RegionLogo',
               existing_type=mysql.VARCHAR(length=255),
               comment='LOGO路径',
               existing_nullable=False)
    op.alter_column('Region', 'EndRegisterDate',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='报名截止日期')
    op.alter_column('Region', 'StartCompetitionDate',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='比赛开始日期')
    op.alter_column('Region', 'EndCompetitionDate',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='比赛结束日期')
    op.create_unique_constraint('uq_create_player_region', 'Team', ['CreatePlayerId', 'RegionId'])
    op.create_unique_constraint('uq_team_name_short_region', 'Team', ['TeamName', 'TeamShortName', 'RegionId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_name_short_region', 'Team', type_='unique')
    op.drop_constraint('uq_create_player_region', 'Team', type_='unique')
    op.alter_column('Region', 'EndCompetitionDate',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='比赛结束日期')
    op.alter_column('Region', 'StartCompetitionDate',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='比赛开始日期')
    op.alter_column('Region', 'EndRegisterDate',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='报名截止日期')
    op.alter_column('Region', 'RegionLogo',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='LOGO路径',
               existing_nullable=False)
    op.alter_column('Region', 'Name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='赛区名',
               existing_nullable=False)
    # ### end Alembic commands ###
