"""Update Database

Revision ID: 558130085d6e
Revises: bfaea6bd2c71
Create Date: 2025-07-18 20:35:23.831942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '558130085d6e'
down_revision: Union[str, None] = 'bfaea6bd2c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Player', 'SecondaryPositionId',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='副位置')
    op.alter_column('Player', 'CurrentRankId',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='当前段位')
    op.alter_column('Player', 'HighestRankId',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='最高段位')
    op.alter_column('Player', 'Contact',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_comment='联系方式')
    op.add_column('Team', sa.Column('TeamShortName', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('Team', 'TeamLogo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='队伍LOGO文件路径')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Team', 'TeamLogo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='队伍LOGO文件路径')
    op.drop_column('Team', 'TeamShortName')
    op.alter_column('Player', 'Contact',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_comment='联系方式')
    op.alter_column('Player', 'HighestRankId',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='最高段位')
    op.alter_column('Player', 'CurrentRankId',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='当前段位')
    op.alter_column('Player', 'SecondaryPositionId',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='副位置')
    # ### end Alembic commands ###
