"""init schema

Revision ID: 715590025621
Revises: 
Create Date: 2025-07-15 10:21:41.708390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '715590025621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContactType',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=255), nullable=False, comment='联系方式'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Grade',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False, comment='段位'),
    sa.Column('Remark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Location',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True, comment='游戏位置：Top、Jungle'),
    sa.Column('Remark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('OperationLog',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='执行者ID（外键可指向 User.Id）'),
    sa.Column('ActionType', sa.String(length=255), nullable=False, comment='操作类型（如：RegisterTeam、ChangeCaptain、QuitTeam）'),
    sa.Column('TargetType', sa.String(length=255), nullable=False, comment='操作对象类型（如：Team、Region、User）'),
    sa.Column('IsSensitive', mysql.TINYINT(display_width=1), nullable=False, comment='是否敏感操作（如权限变更、删人）'),
    sa.Column('TargetId', sa.Integer(), nullable=True, comment='操作目标主键ID'),
    sa.Column('Description', sa.Text(), nullable=True, comment='自然语言或JSON说明（如：{"oldCaptain":1001,"newCaptain":1002}）'),
    sa.Column('IpAddress', sa.String(length=45), nullable=True, comment='操作者IP'),
    sa.Column('UserAgent', sa.Text(), nullable=True, comment='浏览器或客户端标识'),
    sa.Column('Source', sa.String(length=50), nullable=True, comment='来源（Web、API、Admin等）'),
    sa.Column('CreateTime', sa.DateTime(), nullable=True, comment='发生时间'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Permission',
    sa.Column('Id', sa.Integer(), nullable=False, comment='编号'),
    sa.Column('Code', sa.VARCHAR(length=255), nullable=False, comment='权限具体功能，例如：VIEW_MATCH_PAGE、EDIT_PLAYER_API'),
    sa.Column('Name', sa.VARCHAR(length=255), nullable=False, comment='名称'),
    sa.Column('Type', sa.VARCHAR(length=255), nullable=False, comment='权限类型，例如：页面、接口、数据、按钮'),
    sa.Column('Url', sa.VARCHAR(length=255), nullable=True, comment='API请求地址，例如：/admin/match、/api/player/{id}'),
    sa.Column('Method', sa.VARCHAR(length=255), nullable=True, comment='标识GET还是POST请求'),
    sa.Column('Remark', sa.TEXT(), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Role',
    sa.Column('Id', sa.Integer(), nullable=False, comment='角色编号'),
    sa.Column('Name', sa.VARCHAR(length=255), nullable=False, comment='角色名称'),
    sa.Column('Remark', sa.TEXT(), nullable=True, comment='角色备注'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Season',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False, comment='赛季名'),
    sa.Column('StartDate', sa.DateTime(), nullable=False, comment='赛季开始日期'),
    sa.Column('EndDate', sa.DateTime(), nullable=True, comment='赛季结束日期'),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('SystemLog',
    sa.Column('Id', sa.Integer(), nullable=False, comment='日志主键，自增'),
    sa.Column('Level', mysql.VARCHAR(length=255), nullable=False, comment="日志级别，例如：（'Trace', 'Debug', 'Info', 'Warning', 'Error', 'Critical'）"),
    sa.Column('Message', mysql.VARCHAR(length=255), nullable=False, comment='简洁明了的提示语'),
    sa.Column('CreateTime', sa.DateTime(), nullable=False, comment='生成时间'),
    sa.Column('Detail', mysql.TEXT(), nullable=True, comment='异常堆栈、调试信息等'),
    sa.Column('Source', mysql.VARCHAR(length=255), nullable=True, comment='哪个模块或功能写的日志'),
    sa.Column('ServerIp', mysql.VARCHAR(length=255), nullable=True, comment='哪台服务器/容器记录的'),
    sa.Column('TraceId', sa.Integer(), nullable=True, comment='分布式系统中的请求链路标识'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Team',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TeamName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('TeamLogo', mysql.VARCHAR(length=255), nullable=False, comment='队伍LOGO文件路径'),
    sa.Column('CreateUserId', sa.Integer(), nullable=False, comment='队伍创建人编号'),
    sa.Column('CreateCost', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='队伍创建费用'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TeamRole',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('User',
    sa.Column('Id', sa.Integer(), nullable=False, comment='用户编号'),
    sa.Column('UserName', mysql.VARCHAR(length=20), nullable=False, comment='用户名称'),
    sa.Column('Password', mysql.VARCHAR(length=20), nullable=False, comment='密码'),
    sa.Column('UserPhoto', mysql.VARCHAR(length=255), nullable=False, comment='用户头像路径'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Competitor',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='绑定的用户'),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False, comment='用户称呼'),
    sa.Column('GameNameWithNumber', mysql.VARCHAR(length=255), nullable=False, comment='游戏名以及编号'),
    sa.Column('CurrentGradeId', sa.Integer(), nullable=False, comment='当前段位'),
    sa.Column('HighestGradeId', sa.Integer(), nullable=False, comment='最高段位'),
    sa.Column('PrimaryLocationId', sa.Integer(), nullable=False, comment='主位置'),
    sa.Column('SecondaryLocationId', sa.Integer(), nullable=False, comment='副位置'),
    sa.Column('QQ', mysql.VARCHAR(length=20), nullable=False, comment='QQ号'),
    sa.Column('RegisterCost', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='报名押金'),
    sa.Column('RegisterDate', sa.DateTime(), nullable=False, comment='报名日期'),
    sa.Column('IsApproved', mysql.TINYINT(display_width=1), nullable=False, comment='是否通过申请'),
    sa.Column('Reason', sa.Text(), nullable=True, comment='未通过申请原因'),
    sa.ForeignKeyConstraint(['CurrentGradeId'], ['Grade.Id'], name='Competitor_ibfk_2'),
    sa.ForeignKeyConstraint(['HighestGradeId'], ['Grade.Id'], name='Competitor_ibfk_3'),
    sa.ForeignKeyConstraint(['PrimaryLocationId'], ['Location.Id'], name='Competitor_ibfk_4'),
    sa.ForeignKeyConstraint(['SecondaryLocationId'], ['Location.Id'], name='Competitor_ibfk_5'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='Competitor_ibfk_1'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('CurrentGradeId', 'Competitor', ['CurrentGradeId'], unique=False)
    op.create_index('HighestGradeId', 'Competitor', ['HighestGradeId'], unique=False)
    op.create_index('PrimaryLocationId', 'Competitor', ['PrimaryLocationId'], unique=False)
    op.create_index('SecondaryLocationId', 'Competitor', ['SecondaryLocationId'], unique=False)
    op.create_index('UserId', 'Competitor', ['UserId'], unique=False)
    op.create_table('Region',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SeasonId', sa.Integer(), nullable=False, comment='所属赛季'),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='赛区负责人'),
    sa.Column('MaxTeamLimit', sa.Integer(), nullable=False, comment='最大战队上限'),
    sa.Column('EndRegisterDate', sa.DateTime(), nullable=False, comment='报名截止日期'),
    sa.Column('StartCompetitionDate', sa.DateTime(), nullable=False, comment='比赛开始日期'),
    sa.Column('EndCompetitionDate', sa.DateTime(), nullable=False, comment='比赛结束日期'),
    sa.ForeignKeyConstraint(['SeasonId'], ['Season.Id'], name='Region_ibfk_1'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='Region_ibfk_2'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('SeasonId', 'Region', ['SeasonId'], unique=False)
    op.create_index('UserId', 'Region', ['UserId'], unique=False)
    op.create_table('RolePermission',
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('PermissionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionId'], ['Permission.Id'], ),
    sa.ForeignKeyConstraint(['RoleId'], ['Role.Id'], ),
    sa.PrimaryKeyConstraint('RoleId', 'PermissionId')
    )
    op.create_index('PermissionId', 'RolePermission', ['PermissionId'], unique=False)
    op.create_table('TeamJoinApplication',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ApplyType', sa.String(length=255), nullable=False, comment='Join、Invite'),
    sa.Column('FromUserId', sa.Integer(), nullable=True, comment='发起人'),
    sa.Column('ToUserId', sa.Integer(), nullable=True, comment='目标人'),
    sa.Column('TeamId', sa.Integer(), nullable=True, comment='队伍'),
    sa.Column('Message', mysql.TEXT(), nullable=True, comment='申请信息'),
    sa.Column('Status', sa.String(length=255), nullable=True, comment='审批状态：Pending、Approved、Rejected、Cancelled'),
    sa.Column('HandlerUserId', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('HandleTime', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('CreateTime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['FromUserId'], ['User.Id'], name='TeamJoinApplication_ibfk_1'),
    sa.ForeignKeyConstraint(['HandlerUserId'], ['User.Id'], name='TeamJoinApplication_ibfk_4'),
    sa.ForeignKeyConstraint(['TeamId'], ['Team.Id'], name='TeamJoinApplication_ibfk_3'),
    sa.ForeignKeyConstraint(['ToUserId'], ['User.Id'], name='TeamJoinApplication_ibfk_2'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('FromUserId', 'TeamJoinApplication', ['FromUserId'], unique=False)
    op.create_index('HandlerUserId', 'TeamJoinApplication', ['HandlerUserId'], unique=False)
    op.create_index('TeamId', 'TeamJoinApplication', ['TeamId'], unique=False)
    op.create_index('ToUserId', 'TeamJoinApplication', ['ToUserId'], unique=False)
    op.create_table('TeamUser',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TeamId', sa.Integer(), nullable=False, comment='队伍'),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='选手'),
    sa.Column('TeamRoleId', sa.Integer(), nullable=False, comment='队内角色'),
    sa.Column('JoinDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['TeamId'], ['Team.Id'], name='TeamUser_ibfk_1'),
    sa.ForeignKeyConstraint(['TeamRoleId'], ['TeamRole.Id'], name='TeamUser_ibfk_3'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='TeamUser_ibfk_2'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('TeamId', 'TeamUser', ['TeamId'], unique=False)
    op.create_index('TeamRoleId', 'TeamUser', ['TeamRoleId'], unique=False)
    op.create_index('UserId', 'TeamUser', ['UserId'], unique=False)
    op.create_table('UserPermission',
    sa.Column('Id', sa.Integer(), nullable=False, comment='编号'),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='用户编号'),
    sa.Column('PermissionId', sa.Integer(), nullable=False, comment='权限编号'),
    sa.Column('IsAllow', mysql.TINYINT(display_width=1), nullable=False, comment='是否可以使用'),
    sa.ForeignKeyConstraint(['PermissionId'], ['Permission.Id'], name='UserPermission_ibfk_2'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='UserPermission_ibfk_1'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('PermissionId', 'UserPermission', ['PermissionId'], unique=False)
    op.create_index('UserId', 'UserPermission', ['UserId'], unique=False)
    op.create_table('UserRole',
    sa.Column('Id', sa.Integer(), nullable=False, comment='编号'),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='用户编号'),
    sa.Column('RoleId', sa.Integer(), nullable=False, comment='角色编号'),
    sa.ForeignKeyConstraint(['RoleId'], ['Role.Id'], name='UserRoleRole'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='UserRoleUser'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('UserRoleRole', 'UserRole', ['RoleId'], unique=False)
    op.create_index('UserRoleUser', 'UserRole', ['UserId'], unique=False)
    op.create_table('CompetitorContact',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CompetitorId', sa.Integer(), nullable=False, comment='选手编号'),
    sa.Column('ContactTypeId', sa.Integer(), nullable=False, comment='联系类型'),
    sa.Column('ContactNumber', mysql.VARCHAR(length=20), nullable=False, comment='联系号码'),
    sa.ForeignKeyConstraint(['CompetitorId'], ['Competitor.Id'], name='CompetitorContact_ibfk_1'),
    sa.ForeignKeyConstraint(['ContactTypeId'], ['ContactType.Id'], name='CompetitorContact_ibfk_2'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('CompetitorId', 'CompetitorContact', ['CompetitorId'], unique=False)
    op.create_index('ContactTypeId', 'CompetitorContact', ['ContactTypeId'], unique=False)
    op.create_table('RegionTeam',
    sa.Column('TeamId', sa.Integer(), nullable=False),
    sa.Column('RegionId', sa.Integer(), nullable=False),
    sa.Column('RegisterTime', sa.DateTime(), nullable=False, comment='赛区报名时间'),
    sa.Column('AuditStatus', sa.String(length=255), nullable=False, comment='查看审核状态:Pending,Approved,Rejected'),
    sa.ForeignKeyConstraint(['RegionId'], ['Region.Id'], name='RegionTeam_ibfk_2'),
    sa.ForeignKeyConstraint(['TeamId'], ['Team.Id'], name='RegionTeam_ibfk_1'),
    sa.PrimaryKeyConstraint('TeamId', 'RegionId')
    )
    op.create_index('RegionId', 'RegionTeam', ['RegionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('RegionId', table_name='RegionTeam')
    op.drop_table('RegionTeam')
    op.drop_index('ContactTypeId', table_name='CompetitorContact')
    op.drop_index('CompetitorId', table_name='CompetitorContact')
    op.drop_table('CompetitorContact')
    op.drop_index('UserRoleUser', table_name='UserRole')
    op.drop_index('UserRoleRole', table_name='UserRole')
    op.drop_table('UserRole')
    op.drop_index('UserId', table_name='UserPermission')
    op.drop_index('PermissionId', table_name='UserPermission')
    op.drop_table('UserPermission')
    op.drop_index('UserId', table_name='TeamUser')
    op.drop_index('TeamRoleId', table_name='TeamUser')
    op.drop_index('TeamId', table_name='TeamUser')
    op.drop_table('TeamUser')
    op.drop_index('ToUserId', table_name='TeamJoinApplication')
    op.drop_index('TeamId', table_name='TeamJoinApplication')
    op.drop_index('HandlerUserId', table_name='TeamJoinApplication')
    op.drop_index('FromUserId', table_name='TeamJoinApplication')
    op.drop_table('TeamJoinApplication')
    op.drop_index('PermissionId', table_name='RolePermission')
    op.drop_table('RolePermission')
    op.drop_index('UserId', table_name='Region')
    op.drop_index('SeasonId', table_name='Region')
    op.drop_table('Region')
    op.drop_index('UserId', table_name='Competitor')
    op.drop_index('SecondaryLocationId', table_name='Competitor')
    op.drop_index('PrimaryLocationId', table_name='Competitor')
    op.drop_index('HighestGradeId', table_name='Competitor')
    op.drop_index('CurrentGradeId', table_name='Competitor')
    op.drop_table('Competitor')
    op.drop_table('User')
    op.drop_table('TeamRole')
    op.drop_table('Team')
    op.drop_table('SystemLog')
    op.drop_table('Season')
    op.drop_table('Role')
    op.drop_table('Permission')
    op.drop_table('OperationLog')
    op.drop_table('Location')
    op.drop_table('Grade')
    op.drop_table('ContactType')
    # ### end Alembic commands ###
