"""Update Database

Revision ID: a0be69ff9d01
Revises: 558130085d6e
Create Date: 2025-07-19 09:01:55.338798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0be69ff9d01'
down_revision: Union[str, None] = '558130085d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Region', sa.Column('RegionLogo', sa.String(length=255), nullable=False))
    op.alter_column('Team', 'TeamSlogan',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Team', 'TeamSlogan',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('Region', 'RegionLogo')
    # ### end Alembic commands ###
