"""Update Player

Revision ID: bfaea6bd2c71
Revises: de9f9b8ecb69
Create Date: 2025-07-18 10:33:50.258489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfaea6bd2c71'
down_revision: Union[str, None] = 'de9f9b8ecb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('player_user_id_game_name_with_number', 'Player', ['GameNameWithNumber', 'RegionId'])
    op.create_unique_constraint('player_user_id_region_id', 'Player', ['UserId', 'RegionId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_user_id_region_id', 'Player', type_='unique')
    op.drop_constraint('player_user_id_game_name_with_number', 'Player', type_='unique')
    # ### end Alembic commands ###
