"""Update Database

Revision ID: c886ac81e5c4
Revises: 59d3ef7e3781
Create Date: 2025-07-16 14:26:40.848838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c886ac81e5c4'
down_revision: Union[str, None] = '59d3ef7e3781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_role', 'UserRole', ['UserId', 'RoleId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'UserRole', type_='unique')
    # ### end Alembic commands ###
