"""Refactor team

Revision ID: d50ba11e460c
Revises: e63c285cc36d
Create Date: 2025-07-17 11:00:32.054856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd50ba11e460c'
down_revision: Union[str, None] = 'e63c285cc36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('CreatePlayerId', sa.Integer(), nullable=False, comment='队伍创建人编号'))
    op.drop_column('Team', 'CreateUserId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('CreateUserId', mysql.INTEGER(), autoincrement=False, nullable=False, comment='队伍创建人编号'))
    op.drop_column('Team', 'CreatePlayerId')
    # ### end Alembic commands ###
