"""Update Player

Revision ID: de9f9b8ecb69
Revises: 0af6756b936d
Create Date: 2025-07-18 09:31:17.077981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de9f9b8ecb69'
down_revision: Union[str, None] = '0af6756b936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OperationLog',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='执行者ID（外键可指向 User.Id）'),
    sa.Column('ActionType', sa.String(length=255), nullable=False, comment='操作类型（如：RegisterTeam、ChangeCaptain、QuitTeam）'),
    sa.Column('TargetType', sa.String(length=255), nullable=False, comment='操作对象类型（如：Team、Region、User）'),
    sa.Column('IsSensitive', mysql.TINYINT(display_width=1), nullable=False, comment='是否敏感操作（如权限变更、删人）'),
    sa.Column('TargetId', sa.Integer(), nullable=True, comment='操作目标主键ID'),
    sa.Column('Description', sa.Text(), nullable=True, comment='自然语言或JSON说明（如：{"oldCaptain":1001,"newCaptain":1002}）'),
    sa.Column('IpAddress', sa.String(length=45), nullable=True, comment='操作者IP'),
    sa.Column('UserAgent', sa.Text(), nullable=True, comment='浏览器或客户端标识'),
    sa.Column('Source', sa.String(length=50), nullable=True, comment='来源（Web、API、Admin等）'),
    sa.Column('CreateTime', sa.DateTime(), nullable=True, comment='发生时间'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Position',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False, comment='游戏位置：Top、Jungle'),
    sa.Column('Remark', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Rank',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False, comment='段位'),
    sa.Column('Remark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Season',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False, comment='赛季名'),
    sa.Column('StartDate', sa.DateTime(), nullable=False, comment='赛季开始日期'),
    sa.Column('EndDate', sa.DateTime(), nullable=True, comment='赛季结束日期'),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('SystemLog',
    sa.Column('Id', sa.Integer(), nullable=False, comment='日志主键，自增'),
    sa.Column('Level', mysql.VARCHAR(length=255), nullable=False, comment="日志级别，例如：（'Trace', 'Debug', 'Info', 'Warning', 'Error', 'Critical'）"),
    sa.Column('Message', mysql.VARCHAR(length=255), nullable=False, comment='简洁明了的提示语'),
    sa.Column('CreateTime', sa.DateTime(), nullable=False, comment='生成时间'),
    sa.Column('Detail', mysql.TEXT(), nullable=True, comment='异常堆栈、调试信息等'),
    sa.Column('Source', mysql.VARCHAR(length=255), nullable=True, comment='哪个模块或功能写的日志'),
    sa.Column('ServerIp', mysql.VARCHAR(length=255), nullable=True, comment='哪台服务器/容器记录的'),
    sa.Column('TraceId', sa.Integer(), nullable=True, comment='分布式系统中的请求链路标识'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TeamRole',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Region',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SeasonId', sa.Integer(), nullable=False, comment='所属赛季'),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='赛区负责人'),
    sa.Column('MaxTeamLimit', sa.Integer(), nullable=False, comment='最大战队上限'),
    sa.Column('EndRegisterDate', sa.DateTime(), nullable=False, comment='报名截止日期'),
    sa.Column('StartCompetitionDate', sa.DateTime(), nullable=False, comment='比赛开始日期'),
    sa.Column('EndCompetitionDate', sa.DateTime(), nullable=False, comment='比赛结束日期'),
    sa.ForeignKeyConstraint(['SeasonId'], ['Season.Id'], name='Region_ibfk_1'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='Region_ibfk_2'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('SeasonId', 'Region', ['SeasonId'], unique=False)
    op.create_index('UserId', 'Region', ['UserId'], unique=False)
    op.create_table('Player',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False, comment='绑定的用户'),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=False, comment='用户称呼'),
    sa.Column('GameNameWithNumber', mysql.VARCHAR(length=255), nullable=False, comment='游戏名以及编号'),
    sa.Column('CurrentRankId', sa.Integer(), nullable=False, comment='当前段位'),
    sa.Column('HighestRankId', sa.Integer(), nullable=False, comment='最高段位'),
    sa.Column('PrimaryPositionId', sa.Integer(), nullable=False, comment='主位置'),
    sa.Column('SecondaryPositionId', sa.Integer(), nullable=False, comment='副位置'),
    sa.Column('QQ', mysql.VARCHAR(length=20), nullable=False, comment='QQ号'),
    sa.Column('Contact', mysql.VARCHAR(length=20), nullable=False, comment='联系方式'),
    sa.Column('RegionId', sa.Integer(), nullable=False, comment='报名赛区'),
    sa.Column('RegisterCost', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='报名押金'),
    sa.Column('PaymentMethod', mysql.VARCHAR(length=20), nullable=False, comment='支付方式'),
    sa.Column('RegisterTime', sa.DateTime(), nullable=False, comment='赛区报名时间'),
    sa.Column('IsApproved', mysql.TINYINT(display_width=1), nullable=False, comment='是否通过申请'),
    sa.Column('Reason', sa.Text(), nullable=True, comment='未通过申请原因'),
    sa.ForeignKeyConstraint(['CurrentRankId'], ['Rank.Id'], name='Player_ibfk_2'),
    sa.ForeignKeyConstraint(['HighestRankId'], ['Rank.Id'], name='Player_ibfk_3'),
    sa.ForeignKeyConstraint(['PrimaryPositionId'], ['Position.Id'], name='Player_ibfk_4'),
    sa.ForeignKeyConstraint(['RegionId'], ['Region.Id'], name='Player_ibfk_6'),
    sa.ForeignKeyConstraint(['SecondaryPositionId'], ['Position.Id'], name='Player_ibfk_5'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], name='Player_ibfk_1'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('CurrentRankId', 'Player', ['CurrentRankId'], unique=False)
    op.create_index('HighestRankId', 'Player', ['HighestRankId'], unique=False)
    op.create_index('PrimaryPositionId', 'Player', ['PrimaryPositionId'], unique=False)
    op.create_index('RegionId', 'Player', ['RegionId'], unique=False)
    op.create_index('SecondaryPositionId', 'Player', ['SecondaryPositionId'], unique=False)
    op.create_index('UserId', 'Player', ['UserId'], unique=False)
    op.create_table('Team',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TeamName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('TeamLogo', mysql.VARCHAR(length=255), nullable=False, comment='队伍LOGO文件路径'),
    sa.Column('TeamSlogan', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CreatePlayerId', sa.Integer(), nullable=False, comment='队伍创建人编号'),
    sa.Column('RegionId', sa.Integer(), nullable=False, comment='报名赛区'),
    sa.Column('RegisterCost', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='队伍创建费用'),
    sa.Column('RegisterTime', sa.DateTime(), nullable=False, comment='赛区报名时间'),
    sa.ForeignKeyConstraint(['CreatePlayerId'], ['Player.Id'], name='Team_ibfk_2'),
    sa.ForeignKeyConstraint(['RegionId'], ['Region.Id'], name='Team_ibfk_1'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TeamJoinApplication',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ApplyType', sa.String(length=255), nullable=False, comment='Join、Invite'),
    sa.Column('FromPlayerId', sa.Integer(), nullable=True, comment='发起人'),
    sa.Column('ToPlayerId', sa.Integer(), nullable=True, comment='目标人'),
    sa.Column('TeamId', sa.Integer(), nullable=True, comment='队伍'),
    sa.Column('Message', mysql.TEXT(), nullable=True, comment='申请信息'),
    sa.Column('Status', sa.String(length=255), nullable=True, comment='审批状态：Pending、Approved、Rejected、Cancelled'),
    sa.Column('HandlerPlayerId', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('HandleTime', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('CreateTime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['FromPlayerId'], ['Player.Id'], name='TeamJoinApplication_ibfk_1'),
    sa.ForeignKeyConstraint(['HandlerPlayerId'], ['Player.Id'], name='TeamJoinApplication_ibfk_4'),
    sa.ForeignKeyConstraint(['TeamId'], ['Team.Id'], name='TeamJoinApplication_ibfk_3'),
    sa.ForeignKeyConstraint(['ToPlayerId'], ['Player.Id'], name='TeamJoinApplication_ibfk_2'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('FromPlayerId', 'TeamJoinApplication', ['FromPlayerId'], unique=False)
    op.create_index('HandlerPlayerId', 'TeamJoinApplication', ['HandlerPlayerId'], unique=False)
    op.create_index('TeamId', 'TeamJoinApplication', ['TeamId'], unique=False)
    op.create_index('ToPlayerId', 'TeamJoinApplication', ['ToPlayerId'], unique=False)
    op.create_table('TeamPlayer',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TeamId', sa.Integer(), nullable=False, comment='队伍'),
    sa.Column('PlayerId', sa.Integer(), nullable=False, comment='选手'),
    sa.Column('TeamRoleId', sa.Integer(), nullable=False, comment='队内角色'),
    sa.Column('JoinDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PlayerId'], ['Player.Id'], name='TeamPlayer_ibfk_2'),
    sa.ForeignKeyConstraint(['TeamId'], ['Team.Id'], name='TeamPlayer_ibfk_1'),
    sa.ForeignKeyConstraint(['TeamRoleId'], ['TeamRole.Id'], name='TeamPlayer_ibfk_3'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('PlayerId', 'TeamPlayer', ['PlayerId'], unique=False)
    op.create_index('TeamId', 'TeamPlayer', ['TeamId'], unique=False)
    op.create_index('TeamRoleId', 'TeamPlayer', ['TeamRoleId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('TeamRoleId', table_name='TeamPlayer')
    op.drop_index('TeamId', table_name='TeamPlayer')
    op.drop_index('PlayerId', table_name='TeamPlayer')
    op.drop_table('TeamPlayer')
    op.drop_index('ToPlayerId', table_name='TeamJoinApplication')
    op.drop_index('TeamId', table_name='TeamJoinApplication')
    op.drop_index('HandlerPlayerId', table_name='TeamJoinApplication')
    op.drop_index('FromPlayerId', table_name='TeamJoinApplication')
    op.drop_table('TeamJoinApplication')
    op.drop_table('Team')
    op.drop_index('UserId', table_name='Player')
    op.drop_index('SecondaryPositionId', table_name='Player')
    op.drop_index('RegionId', table_name='Player')
    op.drop_index('PrimaryPositionId', table_name='Player')
    op.drop_index('HighestRankId', table_name='Player')
    op.drop_index('CurrentRankId', table_name='Player')
    op.drop_table('Player')
    op.drop_index('UserId', table_name='Region')
    op.drop_index('SeasonId', table_name='Region')
    op.drop_table('Region')
    op.drop_table('TeamRole')
    op.drop_table('SystemLog')
    op.drop_table('Season')
    op.drop_table('Rank')
    op.drop_table('Position')
    op.drop_table('OperationLog')
    # ### end Alembic commands ###
